/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CertificatRouteImport } from './routes/certificat'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CharteEthiqueRouteImport } from './routes/charte-ethique'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as RedacteurRouteImport } from './routes/redacteur'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as PaiementRetourRouteImport } from './routes/paiement.retour'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatRoute = CertificatRouteImport.update({
  id: '/certificat',
  path: '/certificat',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CharteEthiqueRoute = CharteEthiqueRouteImport.update({
  id: '/charte-ethique',
  path: '/charte-ethique',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacteurRoute = RedacteurRouteImport.update({
  id: '/redacteur',
  path: '/redacteur',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PaiementRetourRoute = PaiementRetourRouteImport.update({
  id: '/paiement/retour',
  path: '/paiement/retour',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/cgv': typeof CgvRoute
  '/charte-ethique': typeof CharteEthiqueRoute
  '/client': typeof ClientRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/redacteur': typeof RedacteurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/paiement/retour': typeof PaiementRetourRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/cgv': typeof CgvRoute
  '/charte-ethique': typeof CharteEthiqueRoute
  '/client': typeof ClientRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/redacteur': typeof RedacteurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/paiement/retour': typeof PaiementRetourRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/cgv': typeof CgvRoute
  '/charte-ethique': typeof CharteEthiqueRoute
  '/client': typeof ClientRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/redacteur': typeof RedacteurRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/paiement/retour': typeof PaiementRetourRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/certificat'
    | '/cgv'
    | '/charte-ethique'
    | '/client'
    | '/confidentialite'
    | '/mentions-legales'
    | '/redacteur'
    | '/sitemap.xml'
    | '/profil'
    | '/paiement/retour'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/certificat'
    | '/cgv'
    | '/charte-ethique'
    | '/client'
    | '/confidentialite'
    | '/mentions-legales'
    | '/redacteur'
    | '/sitemap.xml'
    | '/profil'
    | '/paiement/retour'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/certificat'
    | '/cgv'
    | '/charte-ethique'
    | '/client'
    | '/confidentialite'
    | '/mentions-legales'
    | '/redacteur'
    | '/sitemap.xml'
    | '/_authenticated/profil'
    | '/paiement/retour'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CertificatRoute: typeof CertificatRoute
  CgvRoute: typeof CgvRoute
  CharteEthiqueRoute: typeof CharteEthiqueRoute
  ClientRoute: typeof ClientRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RedacteurRoute: typeof RedacteurRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PaiementRetourRoute: typeof PaiementRetourRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificat': {
      id: '/certificat'
      path: '/certificat'
      fullPath: '/certificat'
      preLoaderRoute: typeof CertificatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charte-ethique': {
      id: '/charte-ethique'
      path: '/charte-ethique'
      fullPath: '/charte-ethique'
      preLoaderRoute: typeof CharteEthiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacteur': {
      id: '/redacteur'
      path: '/redacteur'
      fullPath: '/redacteur'
      preLoaderRoute: typeof RedacteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/paiement/retour': {
      id: '/paiement/retour'
      path: '/paiement/retour'
      fullPath: '/paiement/retour'
      preLoaderRoute: typeof PaiementRetourRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CertificatRoute: CertificatRoute,
  CgvRoute: CgvRoute,
  CharteEthiqueRoute: CharteEthiqueRoute,
  ClientRoute: ClientRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RedacteurRoute: RedacteurRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PaiementRetourRoute: PaiementRetourRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
